### ISSUE TITLE
Drag the window anywhere instead of just the title bar

### ISSUE THREAD

**Issue by zfekin** [huynhsontung/Screenbox#127]

**Comment by huynhsontung** [comment]
I think this is a great option to have. I wished I could just move the window by dragging the player surface. I notice you can move the player in Picture in Picture mode in other apps. For Screenbox, do you expect to drag the player in PiP mode only or in normal mode as well?

**Comment by zfekin** [comment]
normal mode

**Comment by zfekin** [comment]
Clicking on any position of the window to drag the window seems to conflict with dragging the progress bar

**Comment by huynhsontung** [comment]
There should be an option in the settings to enable this feature. Since dragging the player area to move the window conflicts with gestures support, users should have the option to disable it, and I think it should be disabled by default. When this mode is active, all gestures are disabled.

We don't need to worry about conflict with the UI controls since the draggable element is rendered underneath all other interactable elements (lower Z-Index). Only the player area would be draggable. All UI elements should function without any issues.

**Comment by huynhsontung** [comment]
After some testing, this feature caused more problems than I originally expected. Pointer logic breaks if we make the whole window draggable. Unfortunately, this might be a no-go for this request.
