### ISSUE TITLE
Hebrew subtitles are displayed as gibberish

### ISSUE THREAD

**Issue by argaman123** [huynhsontung/Screenbox#436]
**Describe the bug**
When I choose any Hebrew subtitles they come out as gibberish, probably an issue with the default encoding. Same subtitles do work as expected in the Windows Media Player.

**Screenshots**
![image](https://github.com/user-attachments/assets/b0aab9ea-4e38-49d7-952c-6b75d2a4d38b)
Instead of: (Windows Media Player)
![image](https://github.com/user-attachments/assets/9d28dcac-c9ca-44cc-9b0d-c56acf6566f0)

**Environment**
OS: Windows 10
Device: PC
App Version v0.13.1.0

**Comment by huynhsontung** [comment]
Hello, sorry for the late response. I was able to replicate the issue but was not able to make it display correctly on Media Player. So far, I have found the fix for Screenbox to enable the Advanced mode in the settings and add this argument in `--subsdec-encoding=ISO-8859-8`.

I don't see a way for the app to automatically fix this. The app can't reliably tell which language the subtitle file is in so it can't apply the proper encoding. Please let me know if the argument fix the problem for you.

**Comment by argaman123** [comment]
Thanks a lot! Works perfectly

**Comment by argaman123** [comment]
Thanks a lot! Works perfectly
